name: eventtoria
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.2

dependencies:
  animations: ^2.0.11
  cloud_firestore: ^6.0.2
  firebase_auth: ^6.1.0
  firebase_core: ^4.1.1
  fl_chart: ^1.1.1
  flutter:
    sdk: flutter
  google_fonts: ^6.3.2
  google_sign_in: ^7.2.0
  provider: ^6.1.5+1
  flutter_launcher_icons: ^0.14.4
  image_picker: ^1.1.1
  dotted_border: ^2.1.0
  lucide_icons_flutter: ^3.1.2
  shared_preferences: ^2.5.3
  google_generative_ai: ^0.4.7
  flutter_markdown: ^0.7.7+1


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  # --- MODIFIED ASSETS SECTION ---
  assets:
    # This line now includes ALL files inside the assets/images/ directory
    - assets/images/ 
    # The separate icon file still needs to be listed
    - assets/icons/AI_logo.jpg
  # -------------------------------


# flutter_launcher_icons configuration
flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/logo.png"